config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :groups_users
  has_many :messages
  has_many :groups_users

  def puts_messages
    if messages.last.try(:image).present?
      '画像が投稿されています'
    elsif messages.last.try(:body)
      messages.last.try(:body)
    else
      'まだメッセージはありません'
    end
  end
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  validates :body, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :groups, through: :groups_users
  has_many :messages
  has_many :groups_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for (resource)
    new_user_registration_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループを作成しました"
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを更新しました"
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :sets_instance, only: [:index, :create]

  def index
    respond_to do |format|
      format.html
      format.json {@reload_message = @group.messages.where('id > ?', params[:last_message_id])}
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージを送信しました" }
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

   private
   def message_params
     params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
   end

   def sets_instance
     @group = Group.find(params[:group_id])
     @groups = current_user.groups
     @message = Message.new
     @messages = @group.messages
   end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # # ...
  #
  # def update
  #   self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
  #   prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
  #
  #   #if update_resource(resource, account_update_params)
  #   if resource.update_without_current_password(account_update_params)
  #     yield resource if block_given?
  #     if is_flashing_format?
  #       flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
  #         :update_needs_confirmation : :updated
  #       set_flash_message :notice, flash_key
  #     end
  #     sign_in resource_name, resource, :bypass => true
  #     respond_with resource, :location => after_update_path_for(resource)
  #   else
  #     clean_up_passwords resource
  #     respond_with resource
  #   end
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    @users_not_current = User.where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end


  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
   params.require(:user).permit(:name, :email)
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.main__sidebar__group
  = link_to group_messages_path(group) do
    .main__sidebar__group-name
      = group.name
    .main__sidebar__group-message
      = group.puts_messages

app/views/groups/_sidebar.html.haml
.header
  .header__sidebar
    .header__sidebar__lists
      %h3.header__sidebar__lists-name
        = current_user.name
      %ul.header__sidebar__lists-icons
        %li.header__sidebar__lists-icons-list
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o
          = link_to edit_user_registration_path do
            %i.fa.fa-cog
  .header__chat
    .header__chat__left
.main
  .main__sidebar
    = render @groups, @messages
  .main__chat
    .main__chat__messages
      .main__chat__messages__body
.footer
  .footer__sidebar
  .footer__chat-group

app/views/groups/_users.html.haml
%li.chat-group-user.clearfix
  .chat-group-user__name
    = user.name
    = hidden_field_tag('group[user_ids][]', user.id)
  .chat-group-user__btn.chat-group-user__btn--remove
    削除

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    - if @group.errors.any?
      #error_explanation
        %h2= "#{@group.errors.count}件のエラーがあります。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :group_name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :group_name, value: "#{@group.name}", placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", :type => "text"}/
          #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            = f.hidden_field :user_ids, value: current_user.id, multiple: true
            %p.chat-group-user__name
            = current_user.name
          = render partial: "groups/users", collection: @users_not_current
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
= render partial: 'groups/sidebar', collection: @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      #error_explanation
        %h2= "#{@group.errors.count}件のエラーがあります。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :group_name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "user-search-field"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input{type: "text", placeholder: "追加したいユーザ名を入力してください", class: "chat-group-form__input", id: "user-search-field", data: {id: "user-id"}}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            = f.hidden_field :user_ids, value: current_user.id, multiple: true
            %p.chat-group-user__name
            = current_user.name
          = render partial: "groups/users", collection: @users_not_current
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "登録する", class: "chat-group-user__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html;, charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.main__chat__messages__body__header{ 'data-message-id':message.id }
  .main__chat__messages__body-user-name
    = message.user.name
  .main__chat__messages__body-date
    = message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.main__chat__messages__body-content{ 'data-last-message-id':message.id }
    = image_tag message.image.to_s if message.try(:image).present?
    = message.body if message.try(:body).present?

app/views/messages/index.html.haml
.flash__message
%header
  .header
    .header__sidebar
      .header__sidebar__lists
        %h3.header__sidebar__lists-name
          = current_user.name
        %ul.header__sidebar__lists-icons
          %li.header__sidebar__lists-icons-list
            = link_to new_group_path do
              %i.fa.fa-pencil-square-o
            = link_to edit_user_registration_path do
              %i.fa.fa-cog
    .header__chat
      .header__chat__left
        .header__chat__left__title
          %h2
            = @group.name
          %ul.header__chat__left__title__members
            Member :
            %li.header__chat__left__title__members-member
              - @group.users.each do |user|
                = "#{user.name},"

      .header__chat__right
        = link_to edit_group_path(@group), class: 'header__chat__right__button' do
          %p Edit
%main
  .main
    .main__sidebar
      = render @groups
    .main__chat
      .main__chat__messages
        .main__chat__messages__body
          .main__chat__messages__body-list
            = render @messages
%footer
  .footer
    .footer__sidebar
    .footer__chat
      .footer__chat__form
        = form_for [@group, @message], html: {class: "footer__chat__form__js-form"} do |f|
          = f.text_field :body, class: "footer__chat__form__js-form__message", placeholder: "type a message"
          %label.footer__chat__form__js-form__mask__image
            %i.fa.fa-picture-o.icon
            = f.file_field :image, class: "hidden js-file", id: "message_image"
            = f.submit 'Send', class: "footer__chat__form__js-form__mask__image__submit"